# Generated by Django 4.2.16 on 2024-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='default-url', help_text='Enter the URL name matching urlpatterns.', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
