# Generated by Django 4.2.16 on 2024-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_remove_category_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='default_url', max_length=100),
        ),
    ]
