# Generated by Django 4.2.16 on 2024-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_event_s_delete_market_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('organizer', models.CharField(max_length=255)),
                ('image_event', models.ImageField(upload_to='event_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='Event_s',
        ),
    ]
