# Generated by Django 4.2.16 on 2024-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_event_s_delete_market_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_s',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event_s',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event_s',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event_s',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event_s',
            name='price',
        ),
        migrations.AddField(
            model_name='event_s',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_s',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event_s',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='event_s',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event_s',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=200),
        ),
        migrations.AddField(
            model_name='event_s',
            name='venue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event_s',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event_s',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
