# Generated by Django 4.2.16 on 2024-11-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_remove_event_s_date_remove_event_s_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='paintings/')),
                ('description', models.TextField()),
            ],
        ),
    ]
